Feature/search engine
CORP-JDP-WABU/FRONTEND.MOVIL.FLUTTER pull request #25
Opened 2024-03-05 04:36 UTC by JuanAyulo

2024-03-05 04:37 UTC, cooper-73 commented on devtools_options.yaml
> +extensions:
Esta linea no va

2024-03-05 06:39 UTC, cooper-73 requested changes

2024-03-05 06:39 UTC, cooper-73 commented on lib/common/widgets/continuous_qualification_object.dart
> +          ElevatedButton(
Use Chips widget

2024-03-05 06:39 UTC, cooper-73 commented on lib/common/widgets/continuous_qualification_object.dart
> +                fontFamily: 'Inter',
We don't use this font family in the project

2024-03-05 06:49 UTC, cooper-73 commented on lib/features/teachers/presentation/widgets/optional_qualifications.dart
> +          selectedRating: const ['No sé', 'Nunca', 'A veces', 'Siempre'],
Replace "No sé" with "-"

2024-03-05 06:51 UTC, cooper-73 requested changes

2024-03-05 06:51 UTC, cooper-73 commented on lib/features/teachers/presentation/widgets/optional_qualifications.dart
> +          selectedRating: const ['No sé', 'Nunca', 'A veces', 'Siempre'],
Replace 'No se' with '-'

2024-03-05 06:51 UTC, cooper-73 commented on lib/features/teachers/presentation/widgets/optional_qualifications.dart
> +          selectedRating: const ['No sé', 'Nunca', 'A veces', 'Siempre'],
Replace "No sé" with "-"

2024-03-05 06:51 UTC, cooper-73 commented on lib/features/teachers/presentation/widgets/optional_qualifications.dart
> +          selectedRating: const ['No sé', 'Nunca', 'A veces', 'Siempre'],
Replace "No sé" with "-"

2024-03-06 03:10 UTC, JuanAyulo commented on lib/common/widgets/continuous_qualification_object.dart
> +                fontFamily: 'Inter',
This font was used on teacher_rating_step 2 in the continous calification part (request by Figma), so as I recycle the same object with new parameters, the style remains the same. If change is needed, please tell me wich font family I must use instead.
![image](https://github.com/CORP-JDP-WABU/FRONTEND.MOVIL.FLUTTER/assets/113644546/6ae1bec7-7f01-477b-9912-b6d44b578d83)

2024-03-07 04:28 UTC, cooper-73 commented on lib/common/widgets/continuous_qualification_object.dart
> +                fontFamily: 'Inter',
Figma seems to be wrong. Default font family should be used. Modification was done.

2024-03-07 04:30 UTC, cooper-73 approved these changes

2024-03-07 04:34 UTC, merged