fixed teacher_profile_screen components
CORP-JDP-WABU/FRONTEND.MOVIL.FLUTTER pull request #33
Opened 2024-03-12 05:48 UTC by JuanAyulo

2024-03-13 05:29 UTC, cooper-73 requested changes

2024-03-13 05:29 UTC, cooper-73 commented on lib/features/teachers/presentation/screens/teacher_profile_screen.dart
> +          Padding(
Unnecessary widget, no need of Padding nor Container

2024-03-13 05:29 UTC, cooper-73 commented on lib/features/teachers/presentation/screens/teacher_profile_screen.dart
> +                        children: [
Center in cross axis

2024-03-13 05:29 UTC, cooper-73 commented on lib/features/teachers/presentation/screens/teacher_profile_screen.dart
> +                          Padding(
Remove padding, manage spacing with sized boxes

2024-03-13 05:29 UTC, cooper-73 commented on lib/features/teachers/presentation/screens/teacher_profile_screen.dart
> +                          const Padding(
Remove padding, manage spacing with sized boxes

2024-03-13 05:29 UTC, cooper-73 commented on lib/features/teachers/presentation/screens/teacher_profile_screen.dart
> +                              alignment: Alignment.centerLeft,
Unnecessary alignment

2024-03-13 05:29 UTC, cooper-73 commented on lib/features/teachers/presentation/screens/teacher_profile_screen.dart
> +                    ] else ...[
Unnecessary wrapping of single element in brackets

2024-03-13 05:29 UTC, cooper-73 commented on lib/features/teachers/presentation/screens/teacher_profile_screen.dart
> +                      Center(
Extract in an unhappy path widget

2024-03-13 05:29 UTC, cooper-73 commented on lib/features/teachers/presentation/screens/teacher_profile_screen.dart
> +                                  fontFamily: 'Gotham Rounded',
Without spaces to reference fontFamily, should be GothamRounded

2024-03-13 05:29 UTC, cooper-73 commented on lib/features/teachers/presentation/screens/teacher_profile_screen.dart
> +                                  color: Color.fromRGBO(191, 191, 191, 1.000),
Colors in hex format

2024-03-13 05:29 UTC, cooper-73 commented on lib/features/teachers/presentation/screens/teacher_profile_screen.dart
> +                                  color: Color.fromRGBO(191, 191, 191, 1.000),
Colors in hex format

2024-03-13 05:29 UTC, cooper-73 commented on lib/features/teachers/presentation/screens/teacher_profile_screen.dart
> +                            const Padding(
Don't use padding for spacing management, with sized boxes (height: xxx)

2024-03-13 05:29 UTC, cooper-73 commented on lib/features/teachers/presentation/screens/teacher_profile_screen.dart
> +                          const Padding(
Same as above, dont use padding and resize spacing

2024-03-13 05:29 UTC, cooper-73 commented on lib/features/teachers/presentation/screens/teacher_profile_screen.dart
> +                        Center(
Use same extracted widget from above

2024-03-13 05:29 UTC, cooper-73 commented on lib/features/teachers/presentation/widgets/teacher_profile_card_details.dart
> +        const SizedBox(height: 16),
Add more spacing, should be 32

2024-03-13 05:29 UTC, cooper-73 commented on lib/features/teachers/presentation/widgets/teacher_profile_card_details.dart
> +            borderRadius: const BorderRadius.vertical(
Use BorderRadius.circular instead

2024-03-13 05:29 UTC, cooper-73 commented on lib/features/teachers/presentation/widgets/teacher_profile_card_details.dart
> +                Material(
Use gradient_circle_avatar from common widgets

2024-03-13 05:29 UTC, cooper-73 commented on lib/features/teachers/presentation/widgets/teacher_profile_card_details.dart
> +                MaterialButton(
Hide unnecessary button, also it could be replaced by custom filled button

2024-03-13 05:29 UTC, cooper-73 commented on lib/features/teachers/presentation/widgets/teacher_profile_card_header.dart
>  import 'package:flutter/material.dart';
Remove this file if it is unused

2024-03-15 03:35 UTC, JuanAyulo commented on lib/features/teachers/presentation/screens/teacher_profile_screen.dart
> +          Padding(
I can't find it

2024-03-15 03:39 UTC, JuanAyulo commented on lib/features/teachers/presentation/screens/teacher_profile_screen.dart
> +                    ] else ...[
if else no brackets needed?

2024-03-15 04:38 UTC, JuanAyulo commented on lib/features/teachers/presentation/widgets/teacher_profile_card_details.dart
> +                MaterialButton(
I prefered this cause, your custom filled button has const padding, that I can change

2024-03-16 03:17 UTC, cooper-73 commented on lib/features/teachers/presentation/screens/teacher_profile_screen.dart
> +                          const Padding(
Remove this padding, it is not necessary anymore as sizedbox is being used for spacing

2024-03-16 03:19 UTC, cooper-73 commented on lib/features/teachers/presentation/screens/teacher_profile_screen.dart
> +                    ] else ...[
I mean square brackets. They are used to treat two or more wigtes as one, but in this case you only have a single widget inside brackets, so it's unnecessary.

2024-03-16 03:19 UTC, cooper-73 commented on lib/features/teachers/presentation/screens/teacher_profile_screen.dart
> +                          const Padding(
Remove padding, as sized box is being used

2024-03-16 03:20 UTC, cooper-73 commented on lib/features/teachers/presentation/widgets/teacher_profile_card_details.dart
> +                MaterialButton(
Dropped it, 'cause there is no logic for this button now.

2024-03-16 03:22 UTC, cooper-73 commented on lib/features/teachers/presentation/screens/teacher_profile_screen.dart
> +                    ] else ...[
Same, no need of square brackets, as it is a single element

2024-03-22 05:47 UTC, cooper-73 approved these changes

2024-03-22 05:51 UTC, merged